# Generated by Django 5.1.2 on 2024-10-23 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField()),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=200)),
                ('parent_dept_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='LeaveTypes',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_name', models.CharField()),
                ('days', models.IntegerField()),
            ],
            options={
                'db_table': 'leave_types',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=169)),
                ('work_start', models.TimeField()),
                ('work_end', models.TimeField()),
                ('department_id', models.IntegerField(default=0)),
                ('manager_id', models.IntegerField(default=0)),
                ('position', models.CharField(max_length=100)),
                ('hired_date', models.DateField()),
                ('left_date', models.DateField(null=True)),
                ('profile_picture', models.ImageField(upload_to='media/employees/')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.countries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeBalances',
            fields=[
                ('eb_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_left', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.leavetypes')),
            ],
            options={
                'db_table': 'employee_balances',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('allowance_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('days', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employees')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetypes')),
            ],
            options={
                'db_table': 'employee_allowance',
                'unique_together': {('employee', 'leave_type', 'period_start_date', 'period_end_date')},
            },
        ),
        migrations.CreateModel(
            name='NonWorkingDays',
            fields=[
                ('nwd_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countries')),
            ],
            options={
                'db_table': 'non_working_days',
            },
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('WAITING', 'Waiting'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='WAITING', max_length=10)),
                ('status_change', models.DateTimeField(auto_now=True)),
                ('approver', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_approver', to='api.employees')),
                ('employee', models.ManyToManyField(related_name='requests_employee', to='api.employees')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.leavetypes')),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='WriteOffs',
            fields=[
                ('wo_id', models.AutoField(primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees')),
                ('employee_allowance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employeeallowance')),
            ],
            options={
                'db_table': 'write_offs',
            },
        ),
        migrations.CreateModel(
            name='Substitutes',
            fields=[
                ('substitute_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employees')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.requests')),
            ],
            options={
                'db_table': 'substitutes',
                'unique_together': {('request_id', 'employee_id')},
            },
        ),
    ]
