# Generated by Django 5.1.4 on 2024-12-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='default_bring_forward_days',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
