# Generated by Django 5.1.2 on 2024-10-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='left_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
