# Generated by Django 5.1.2 on 2024-11-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('can_add_employee', 'Can add an employee'), ('can_update_employee', 'Can update an employee'), ('can_delete_employee', 'Can delete an employee')]},
        ),
    ]
