# Generated by Django 5.1.4 on 2024-12-29 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_leavetype_default_bring_forward_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('LEFT', 'Left'), ('FIRED', 'Fired')], default='ACTIVE', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='employeeallowance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employeeallowance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype'),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype'),
        ),
    ]
