# Generated by Django 5.1.2 on 2024-11-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('crud_employee', 'Can add, update and delete an employee')]},
        ),
    ]
