# Generated by Django 5.1.4 on 2024-12-30 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.countries'),
        ),
    ]
