# Generated by Django 5.1.3 on 2024-11-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeBalances',
            new_name='EmployeeBalance',
        ),
        migrations.RenameModel(
            old_name='WriteOffs',
            new_name='WriteOff',
        ),
    ]
