# Generated by Django 5.1.3 on 2024-11-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_employeebalances_employeebalance_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonWorkingDays',
            new_name='NonWorkingDay',
        ),
    ]
