# Generated by Django 5.1.4 on 2024-12-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.JSONField(default=['Employee'], help_text='List of roles assigned to the employee'),
        ),
    ]
