# Generated by Django 5.1.4 on 2024-12-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_employee_options_employee_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='roles',
            field=models.JSONField(default=list, help_text='List of roles assigned to the employee'),
        ),
    ]
