# Generated by Django 5.1.4 on 2024-12-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employee_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='roles',
        ),
    ]
