# Generated by Django 5.1.4 on 2024-12-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_employee_phone_number_alter_employee_left_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.countries'),
        ),
    ]
