# Generated by Django 5.1.4 on 2024-12-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_employee_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.JSONField(default=list, help_text='List of roles assigned to the employee'),
        ),
    ]
