# Generated by Django 5.1.4 on 2024-12-13 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_employee_middle_name_alter_employee_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('owner', 'Can do everything'), ('HR', 'Can add, edit, delete people, leave types, countries etc'), ('export_records', 'Can see and export records of requests')]},
        ),
    ]
