# Generated by Django 5.1.4 on 2025-01-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_employee_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager_id',
        ),
    ]
