# Generated by Django 5.1.4 on 2024-12-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employee_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('Owner', 'Can do everything'), ('HR', 'Can add, edit and delete people, leave types, countries etc and and export records of requests'), ('Manager', 'Can check certain things for his team etc')]},
        ),
    ]
