# Generated by Django 5.1.4 on 2025-01-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_writeoff_employee_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBalance',
            fields=[
                ('eb_id', models.AutoField(primary_key=True, serialize=False)),
                ('days_left', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
            options={
                'db_table': 'employee_balances',
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('wo_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('initial_days', models.IntegerField(default=0)),
                ('days_brought_forward', models.IntegerField(default=0)),
                ('days_lost', models.IntegerField(default=0)),
                ('employee_balance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employeebalance')),
            ],
            options={
                'db_table': 'write_offs',
            },
        ),
    ]
