# Generated by Django 5.1.4 on 2025-01-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_employeebalance_writeoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebalance',
            name='period_end_date',
            field=models.DateField(default="2024-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeebalance',
            name='period_start_date',
            field=models.DateField(default="2024-12-31"),
            preserve_default=False,
        ),
    ]
