# Generated by Django 5.1.4 on 2025-01-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_employeebalance_period_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeebalance',
            name='period_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employeebalance',
            name='period_start_date',
            field=models.DateField(),
        ),
    ]
