# Generated by Django 5.1.4 on 2025-01-05 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_employeebalance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeebalance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='employeebalance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeebalance',
            name='leave_type',
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('balance_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('days', models.FloatField()),
                ('bring_forward', models.IntegerField(blank=True, null=True)),
                ('days_used', models.FloatField(default=0)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.leavetype')),
            ],
            options={
                'db_table': 'employee_leave_balances',
                'unique_together': {('employee', 'leave_type', 'period_start_date', 'period_end_date')},
            },
        ),
        migrations.AlterField(
            model_name='writeoff',
            name='employee_balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employeeleavebalance'),
        ),
        migrations.DeleteModel(
            name='EmployeeAllowance',
        ),
        migrations.DeleteModel(
            name='EmployeeBalance',
        ),
    ]
