# Generated by Django 5.1.4 on 2025-01-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_employeebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LEFT', 'Left'), ('FIRED', 'Fired')], default='ACTIVE', max_length=10, null=True),
        ),
    ]
