# Generated by Django 5.1.4 on 2025-01-09 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteWork',
            fields=[
                ('remote_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('WAITING', 'Waiting'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='WAITING', max_length=10)),
                ('status_change', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('approver', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remote_approver', to='api.employee')),
                ('employee', models.ManyToManyField(related_name='remote_employee', to='api.employee')),
            ],
        ),
    ]
