# Generated by Django 5.1.4 on 2025-01-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remotework'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='HolidayRequest',
        ),
        migrations.AlterModelTable(
            name='holidayrequest',
            table='holiday_requests',
        ),
    ]
