# Generated by Django 5.1.4 on 2025-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_remotework_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayrequest',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='remotework',
            name='approver',
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='approver',
            field=models.ManyToManyField(related_name='requests_approver', to='api.employee'),
        ),
        migrations.AddField(
            model_name='remotework',
            name='approver',
            field=models.ManyToManyField(related_name='remote_approver', to='api.employee'),
        ),
    ]
