# Generated by Django 5.1.4 on 2025-01-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_holidayrequest_approver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holidayrequest',
            name='approver',
        ),
        migrations.RemoveField(
            model_name='remotework',
            name='approver',
        ),
        migrations.AddField(
            model_name='holidayrequest',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requests_approver', to='api.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotework',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remote_approver', to='api.employee'),
            preserve_default=False,
        ),
    ]
