# Generated by Django 5.1.4 on 2025-01-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_holidayrequest_approver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holidayrequest',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='remotework',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
