# Generated by Django 5.1.4 on 2025-01-22 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_holidayrequest_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotework',
            name='employee',
        ),
        migrations.AddField(
            model_name='remotework',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remote_employee', to='api.employee'),
            preserve_default=False,
        ),
    ]
