# Generated by Django 5.1.4 on 2025-02-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_remotework_employee_remotework_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeBalanceChange',
        ),
    ]
