version: '3.0'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
    depends_on:
      - database
    volumes:
      - ./backend:/backend
      
  database:
    image: postgres:latest
    env_file:
      - database_files/database.env
    ports:
      - "6543:5432"
    volumes:
      - database-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Default for Vite dev env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  database-data: